import { createContext, useContext, useState, useEffect } from 'react';

// Görev 41: Çoklu dil desteği (TR/EN). Kütüphanesiz, ThemeContext deseniyle.
const STORAGE_KEY = 'crypto-tracker-lang';

const translations = {
  tr: {
    // Navbar
    'nav.home': 'Ana Sayfa',
    'nav.leaderboard': 'Liderlik Tablosu',
    'nav.compare': 'Karşılaştır',
    'nav.converter': 'Dönüştürücü',
    'nav.feedback': 'Geri Bildirim',
    'nav.bots': '🤖 Botlarım',
    'nav.watchlist': '🌟 Favorilerim 🌟',
    'nav.portfolio': 'Portföyüm',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin Paneli',
    'nav.signin': 'Giriş Yap',
    'nav.signup': 'Kayıt Ol',
    'nav.logout': 'Çıkış Yap',
    // Profil
    'profile.title': 'Profil',
    'profile.info': 'Bilgilerim',
    'profile.username': 'Kullanıcı Adı',
    'profile.email': 'Email',
    'profile.roles': 'Roller',
    'profile.memberSince': 'Üyelik Tarihi',
    'profile.uploadPhoto': 'Fotoğraf Yükle',
    'profile.edit': 'Profili Düzenle',
    'profile.save': 'Kaydet',
    'profile.changePassword': 'Şifre Değiştir',
    'profile.myAlerts': 'Alarmlarım',
    'profile.emailNotifications': 'E-posta bildirimleri (alarm/bot sinyalleri)',
    'profile.interval': 'Aralık',
    'profile.status': 'Durum',
    'profile.active': 'Aktif',
    'profile.passive': 'Pasif',
    'profile.activate': 'Aktifleştir',
    'profile.deactivate': 'Pasifleştir',
    // Giriş / Kayıt
    'auth.signinTitle': 'Giriş Yap',
    'auth.signupTitle': 'Kayıt Ol',
    'auth.usernameOrEmail': 'Kullanıcı Adı veya Email',
    'auth.usernameOrEmailPlaceholder': 'Kullanıcı adınızı veya e-postanızı girin',
    'auth.password': 'Şifre',
    'auth.passwordPlaceholder': 'Şifrenizi girin',
    'auth.noAccount': 'Hesabın yok mu?',
    'auth.forgotPassword': 'Şifreni mi unuttun?',
    'auth.loginFailed': 'Giriş başarısız. Bilgilerinizi kontrol edin.',
    'auth.usernameOrEmailRequired': 'Kullanıcı adı veya e-posta alanı boş bırakılamaz.',
    'auth.passwordRequired': 'Şifre alanı boş bırakılamaz.',
    'auth.passwordMinLength': 'Şifre en az 6 karakter olmalıdır.',
    // Kayıt
    'signup.username': 'Kullanıcı Adı',
    'signup.usernamePlaceholder': 'Kullanıcı adınızı belirleyin',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'E-posta adresinizi girin',
    'signup.passwordPlaceholder': 'Güçlü bir şifre girin',
    'signup.confirmPassword': 'Şifre Tekrar',
    'signup.confirmPasswordPlaceholder': 'Şifrenizi tekrar girin',
    'signup.backToSignin': 'Giriş sayfasına dön',
    'signup.usernameRequired': 'Kullanıcı adı alanı boş bırakılamaz.',
    'signup.emailRequired': 'Email alanı boş bırakılamaz.',
    'signup.emailInvalid': 'Geçerli bir e-posta adresi giriniz.',
    'signup.confirmPasswordRequired': 'Şifre tekrar alanı boş bırakılamaz.',
    'signup.passwordsMismatch': 'Şifreler eşleşmiyor.',
    'signup.registerFailed': 'Kayıt başarısız. Lütfen tekrar deneyin.',
    'signup.successMessage': 'Kaydınız alındı. Hesabınızı etkinleştirmek için e-postanıza gönderilen doğrulama bağlantısına tıklayın.',
    // Ana sayfa
    'home.topGainers': '↗ Top 5 Yükselen',
    'home.topLosers': '↘ Top 5 Düşen',
    'home.allMarket': 'Tüm Kripto Para Piyasası',
    'home.noGainers': 'Yükseliş yaşayan varlık bulunmuyor.',
    'home.noLosers': 'Düşüş yaşayan varlık bulunmuyor. 🚀',
    // Karşılaştırma
    'compare.title': 'Coin Karşılaştırma',
    'compare.subtitle': 'İki coini seçip güncel piyasa verilerini yan yana karşılaştırın.',
    'compare.metric': 'Metrik',
    'compare.currentPrice': 'Güncel Fiyat',
    'compare.change24h': '24s Değişim',
    'compare.high24h': '24s En Yüksek',
    'compare.low24h': '24s En Düşük',
    'compare.loadingPrices': 'Fiyatlar yükleniyor... (canlı veri birkaç saniye içinde gelir)',
    // Portföy
    'portfolio.loading': 'Portföy verileri yükleniyor...',
    'portfolio.title': 'Portföyüm',
    'portfolio.availableBalance': 'Kullanılabilir Bakiye',
    'portfolio.totalValue': 'Toplam Portföy Değeri',
    'portfolio.totalPnL': 'Genel Kâr/Zarar',
    'portfolio.distribution': 'Portföy Dağılımı',
    'portfolio.myAssets': 'Varlıklarım',
    'portfolio.coin': 'Coin',
    'portfolio.quantity': 'Miktar',
    'portfolio.avgBuyPrice': 'Ortalama Alış Fiyatı',
    'portfolio.currentPrice': 'Güncel Fiyat',
    'portfolio.currentValue': 'Güncel Değer',
    'portfolio.pnlPercent': 'Kâr / Zarar %',
    'portfolio.noCoins': 'Henüz sahip olduğunuz bir coin bulunmuyor.',
    'portfolio.txHistory': 'İşlem Geçmişi',
    'portfolio.allTx': 'Tüm işlemler',
    'portfolio.onlyBuy': 'Sadece Alım',
    'portfolio.onlySell': 'Sadece Satım',
    'portfolio.date': 'Tarih',
    'portfolio.txType': 'İşlem Türü',
    'portfolio.txPrice': 'İşlem Fiyatı',
    'portfolio.noTx': 'Bu kritere uygun işlem bulunmuyor.',
    'portfolio.prev': '← Önceki',
    'portfolio.next': 'Sonraki →',
    'portfolio.page': 'Sayfa',
    'portfolio.buy': 'ALIM',
    'portfolio.sell': 'SATIM',
    // Geri bildirim
    'feedback.title': 'Geri Bildirim',
    'feedback.message': 'Mesaj',
    'feedback.rating': 'Puan (1-5)',
    'feedback.noRating': 'Puan vermek istemiyorum',
    'feedback.send': 'Gönder',
    'feedback.success': 'Geri bildiriminiz başarıyla gönderildi.',
    'feedback.error': 'Gönderme işlemi başarısız.',
    // Şifre sıfırlama
    'forgot.title': 'Şifremi Unuttum',
    'forgot.subtitle': 'Şifre sıfırlama bağlantısı oluşturmak için e-posta adresinizi girin.',
    'forgot.error': 'İşlem başarısız oldu.',
    'forgot.sending': 'Gönderiliyor...',
    'forgot.submit': 'Sıfırlama Bağlantısı Oluştur',
    // E-posta doğrulama
    'confirm.title': 'E-posta Doğrulama',
    'confirm.verifying': 'Doğrulanıyor, lütfen bekleyin...',
    'confirm.signin': 'Giriş yap',
    'confirm.retrySignup': 'Yeniden kayıt ol',
    'confirm.failed': 'Doğrulama başarısız. Bağlantı geçersiz veya süresi dolmuş olabilir.',
    // Şifre yenileme
    'reset.title': 'Yeni Şifre Belirle',
    'reset.newPassword': 'Yeni Şifre',
    'reset.confirmPassword': 'Yeni Şifre (Tekrar)',
    'reset.submit': 'Şifreyi Güncelle',
    'reset.success': 'Şifreniz güncellendi. Giriş yapabilirsiniz.',
    'reset.mismatch': 'Şifreler eşleşmiyor.',
    // Dönüştürücü
    'converter.eyebrow': 'Kripto Dönüştürücü',
    'converter.title': 'Coin miktarını USD ve TRY değerine çevir',
    'converter.amount': 'Miktar',
    'converter.coinPlaceholder': 'BTC, ETH, Bitcoin, Ethereum...',
    'converter.amountPlaceholder': 'Örn: 1.5',
    'converter.noResult': 'Sonuç bulunamadı',
    // Favoriler
    'watchlist.title': '⭐ Favorilerim',
    'watchlist.empty': 'Henüz favori yok',
    'watchlist.emptyText': 'Ana sayfada coin kartlarındaki yıldıza tıklayarak favorilerine ekleyebilirsin.',
    // Bot
    'bot.title': '🤖 Alım-Satım Botu Yönetimi',
    'bot.newBot': 'Yeni Bot Kur',
    'bot.myBots': 'Mevcut Botlarım',
    'bot.symbol': 'Sembol',
    'bot.amount': 'Miktar',
    'bot.status': 'Durum',
    'bot.action': 'İşlem',
    'bot.stop': 'Durdur',
    'bot.start': 'Başlat',
    'bot.loading': 'Botlar yükleniyor...',
    // Dashboard
    'dashboard.unauthorized': 'Yetkisiz Erişim!',
    'dashboard.adminPanel': 'Admin Paneli',
    'dashboard.reports': '📊 Sistem Özet Raporları',
    'dashboard.totalUsers': 'Toplam Kullanıcı',
    'dashboard.activeCoins': 'Aktif Kripto Paralar',
    'dashboard.dailyVolume': 'Günlük İşlem Hacmi',
    'dashboard.userMgmt': 'Kullanıcı Yönetimi Tablosu',
    'dashboard.feedbacks': '💬 Geri Bildirimler',
    'dashboard.auditLog': '📋 Denetim Günlüğü',
    'dashboard.searchUser': 'Kullanıcı veya E-posta ara...',
    'dashboard.message': 'Mesaj',
    'dashboard.score': 'Puan',
    'dashboard.date': 'Tarih',
    'dashboard.guest': 'Misafir',
    'dashboard.noFeedback': 'Henüz geri bildirim bulunmuyor.',
    'dashboard.admin': 'Yönetici',
    'dashboard.action': 'İşlem',
    'dashboard.target': 'Hedef',
    'dashboard.detail': 'Detay',
    // Coin detay
    'coin.notFound': 'Coin Bulunamadı',
    'coin.setAlarm': 'Alarm Kur',
    'coin.signinToAlarm': 'Alarm kurmak için',
    'coin.signin': 'giriş yapın',
    'coin.alarmType': 'Alarm Tipi',
    'coin.targetPriceType': 'Hedef Fiyat',
    'coin.percentType': 'Yüzde Değişim',
    'coin.targetPriceLabel': 'Hedef Fiyat (USD)',
    'coin.percentLabel': 'Yüzde Değişim (%)',
    'coin.direction': 'Yön',
    'coin.priceUp': 'Yukarı (fiyat hedefin üstüne çıkınca)',
    'coin.priceDown': 'Aşağı (fiyat hedefin altına inince)',
    'coin.percentUp': 'Yükseliş (referanstan %X yükselince)',
    'coin.percentDown': 'Düşüş (referanstan %X düşünce)',
    'coin.frequency': 'Kontrol Sıklığı',
    'coin.minutely': 'Dakikalık',
    'coin.hourly': 'Saatlik',
    'coin.daily': 'Günlük',
    'coin.percentPlaceholder': 'Örn. 5',
    // Liderlik tablosu
    'leaderboard.title': '🏆 Liderlik Tablosu (Top 10)',
    'leaderboard.subtitle': 'Sanal bakiye ve portföy performansına göre en yüksek kâr oranına sahip kullanıcılar listelenmektedir.',
    'leaderboard.error': 'Liderlik tablosu verileri yüklenirken bir sorun oluştu.',
    'leaderboard.empty': 'Henüz sıralama verisi bulunmuyor.',
    // Genel
    'common.loading': 'Yükleniyor...',
    'common.language': 'Dil',
  },
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.leaderboard': 'Leaderboard',
    'nav.compare': 'Compare',
    'nav.converter': 'Converter',
    'nav.feedback': 'Feedback',
    'nav.bots': '🤖 My Bots',
    'nav.watchlist': '🌟 Watchlist 🌟',
    'nav.portfolio': 'My Portfolio',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin Panel',
    'nav.signin': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.logout': 'Log Out',
    // Profile
    'profile.title': 'Profile',
    'profile.info': 'My Info',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.roles': 'Roles',
    'profile.memberSince': 'Member Since',
    'profile.uploadPhoto': 'Upload Photo',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save',
    'profile.changePassword': 'Change Password',
    'profile.myAlerts': 'My Alerts',
    'profile.emailNotifications': 'Email notifications (alert/bot signals)',
    'profile.interval': 'Interval',
    'profile.status': 'Status',
    'profile.active': 'Active',
    'profile.passive': 'Passive',
    'profile.activate': 'Activate',
    'profile.deactivate': 'Deactivate',
    // Sign in / Sign up
    'auth.signinTitle': 'Sign In',
    'auth.signupTitle': 'Sign Up',
    'auth.usernameOrEmail': 'Username or Email',
    'auth.usernameOrEmailPlaceholder': 'Enter your username or email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.noAccount': "Don't have an account?",
    'auth.forgotPassword': 'Forgot your password?',
    'auth.loginFailed': 'Login failed. Please check your credentials.',
    'auth.usernameOrEmailRequired': 'Username or email cannot be empty.',
    'auth.passwordRequired': 'Password cannot be empty.',
    'auth.passwordMinLength': 'Password must be at least 6 characters.',
    // Sign up
    'signup.username': 'Username',
    'signup.usernamePlaceholder': 'Choose a username',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.passwordPlaceholder': 'Enter a strong password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.confirmPasswordPlaceholder': 'Re-enter your password',
    'signup.backToSignin': 'Back to sign in',
    'signup.usernameRequired': 'Username cannot be empty.',
    'signup.emailRequired': 'Email cannot be empty.',
    'signup.emailInvalid': 'Please enter a valid email address.',
    'signup.confirmPasswordRequired': 'Confirm password cannot be empty.',
    'signup.passwordsMismatch': 'Passwords do not match.',
    'signup.registerFailed': 'Registration failed. Please try again.',
    'signup.successMessage': 'Registration received. Click the verification link sent to your email to activate your account.',
    // Home
    'home.topGainers': '↗ Top 5 Gainers',
    'home.topLosers': '↘ Top 5 Losers',
    'home.allMarket': 'All Crypto Market',
    'home.noGainers': 'No gaining assets.',
    'home.noLosers': 'No losing assets. 🚀',
    // Compare
    'compare.title': 'Coin Comparison',
    'compare.subtitle': 'Pick two coins and compare their current market data side by side.',
    'compare.metric': 'Metric',
    'compare.currentPrice': 'Current Price',
    'compare.change24h': '24h Change',
    'compare.high24h': '24h High',
    'compare.low24h': '24h Low',
    'compare.loadingPrices': 'Loading prices... (live data arrives in a few seconds)',
    // Portfolio
    'portfolio.loading': 'Loading portfolio data...',
    'portfolio.title': 'My Portfolio',
    'portfolio.availableBalance': 'Available Balance',
    'portfolio.totalValue': 'Total Portfolio Value',
    'portfolio.totalPnL': 'Total P&L',
    'portfolio.distribution': 'Portfolio Distribution',
    'portfolio.myAssets': 'My Assets',
    'portfolio.coin': 'Coin',
    'portfolio.quantity': 'Quantity',
    'portfolio.avgBuyPrice': 'Avg. Buy Price',
    'portfolio.currentPrice': 'Current Price',
    'portfolio.currentValue': 'Current Value',
    'portfolio.pnlPercent': 'P&L %',
    'portfolio.noCoins': 'You do not own any coins yet.',
    'portfolio.txHistory': 'Transaction History',
    'portfolio.allTx': 'All transactions',
    'portfolio.onlyBuy': 'Buys only',
    'portfolio.onlySell': 'Sells only',
    'portfolio.date': 'Date',
    'portfolio.txType': 'Type',
    'portfolio.txPrice': 'Price',
    'portfolio.noTx': 'No transactions match this filter.',
    'portfolio.prev': '← Previous',
    'portfolio.next': 'Next →',
    'portfolio.page': 'Page',
    'portfolio.buy': 'BUY',
    'portfolio.sell': 'SELL',
    // Feedback
    'feedback.title': 'Feedback',
    'feedback.message': 'Message',
    'feedback.rating': 'Rating (1-5)',
    'feedback.noRating': "I don't want to rate",
    'feedback.send': 'Send',
    'feedback.success': 'Your feedback was sent successfully.',
    'feedback.error': 'Failed to send.',
    // Forgot password
    'forgot.title': 'Forgot Password',
    'forgot.subtitle': 'Enter your email to create a password reset link.',
    'forgot.error': 'Operation failed.',
    'forgot.sending': 'Sending...',
    'forgot.submit': 'Create Reset Link',
    // Email verification
    'confirm.title': 'Email Verification',
    'confirm.verifying': 'Verifying, please wait...',
    'confirm.signin': 'Sign in',
    'confirm.retrySignup': 'Sign up again',
    'confirm.failed': 'Verification failed. The link may be invalid or expired.',
    // Password reset
    'reset.title': 'Set a New Password',
    'reset.newPassword': 'New Password',
    'reset.confirmPassword': 'New Password (again)',
    'reset.submit': 'Update Password',
    'reset.success': 'Your password has been updated. You can sign in now.',
    'reset.mismatch': 'Passwords do not match.',
    // Converter
    'converter.eyebrow': 'Crypto Converter',
    'converter.title': 'Convert a coin amount to USD and TRY',
    'converter.amount': 'Amount',
    'converter.coinPlaceholder': 'BTC, ETH, Bitcoin, Ethereum...',
    'converter.amountPlaceholder': 'e.g. 1.5',
    'converter.noResult': 'No result found',
    // Watchlist
    'watchlist.title': '⭐ Watchlist',
    'watchlist.empty': 'No favorites yet',
    'watchlist.emptyText': 'Add favorites by clicking the star on coin cards on the home page.',
    // Bot
    'bot.title': '🤖 Trading Bot Management',
    'bot.newBot': 'Create New Bot',
    'bot.myBots': 'My Bots',
    'bot.symbol': 'Symbol',
    'bot.amount': 'Amount',
    'bot.status': 'Status',
    'bot.action': 'Action',
    'bot.stop': 'Stop',
    'bot.start': 'Start',
    'bot.loading': 'Loading bots...',
    // Dashboard
    'dashboard.unauthorized': 'Unauthorized Access!',
    'dashboard.adminPanel': 'Admin Panel',
    'dashboard.reports': '📊 System Summary Reports',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.activeCoins': 'Active Cryptocurrencies',
    'dashboard.dailyVolume': 'Daily Transaction Volume',
    'dashboard.userMgmt': 'User Management Table',
    'dashboard.feedbacks': '💬 Feedback',
    'dashboard.auditLog': '📋 Audit Log',
    'dashboard.searchUser': 'Search user or email...',
    'dashboard.message': 'Message',
    'dashboard.score': 'Rating',
    'dashboard.date': 'Date',
    'dashboard.guest': 'Guest',
    'dashboard.noFeedback': 'No feedback yet.',
    'dashboard.admin': 'Admin',
    'dashboard.action': 'Action',
    'dashboard.target': 'Target',
    'dashboard.detail': 'Detail',
    // Coin detail
    'coin.notFound': 'Coin Not Found',
    'coin.setAlarm': 'Set Alarm',
    'coin.signinToAlarm': 'To set an alarm,',
    'coin.signin': 'sign in',
    'coin.alarmType': 'Alarm Type',
    'coin.targetPriceType': 'Target Price',
    'coin.percentType': 'Percent Change',
    'coin.targetPriceLabel': 'Target Price (USD)',
    'coin.percentLabel': 'Percent Change (%)',
    'coin.direction': 'Direction',
    'coin.priceUp': 'Up (when price rises above target)',
    'coin.priceDown': 'Down (when price falls below target)',
    'coin.percentUp': 'Rise (when it rises X% from reference)',
    'coin.percentDown': 'Fall (when it falls X% from reference)',
    'coin.frequency': 'Check Frequency',
    'coin.minutely': 'Every minute',
    'coin.hourly': 'Hourly',
    'coin.daily': 'Daily',
    'coin.percentPlaceholder': 'e.g. 5',
    // Leaderboard
    'leaderboard.title': '🏆 Leaderboard (Top 10)',
    'leaderboard.subtitle': 'Users with the highest profit rate based on virtual balance and portfolio performance are listed.',
    'leaderboard.error': 'A problem occurred while loading leaderboard data.',
    'leaderboard.empty': 'No ranking data yet.',
    // Common
    'common.loading': 'Loading...',
    'common.language': 'Language',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'tr' || saved === 'en' ? saved : 'tr';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  // Çeviri anahtarını mevcut dile çevirir; bulunamazsa anahtarı döndürür.
  const t = (key) => translations[lang]?.[key] ?? key;
  const toggleLang = () => setLang((l) => (l === 'tr' ? 'en' : 'tr'));

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider');
  return ctx;
}
